/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gustavo.guardarlibros.vista;

import com.gustavo.guardarlibros.modelo.Lectura;
import com.gustavo.guardarlibros.modelo.Libro;
import com.gustavo.guardarlibros.modelo.Perfil;
import com.gustavo.guardarlibros.utils.LecturaUtilImpl;
import com.gustavo.guardarlibros.utils.LibroUtilImpl;
import java.awt.BorderLayout;
import java.awt.RenderingHints;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.IntSummaryStatistics;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author gusta
 */
public class JDialogEstadisticaEstadoDeMisLibros extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEstadisticaEstadoDeMisLibros.class.getName());

    private Perfil perfil = new Perfil();

    private LecturaUtilImpl lecturaUtilImpl = new LecturaUtilImpl();

    /**
     * Creates new form JDialogEstadisticaProgresoPorLibro
     */
    public JDialogEstadisticaEstadoDeMisLibros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public JDialogEstadisticaEstadoDeMisLibros(java.awt.Frame parent, boolean modal, Perfil perfil) {
        super(parent, modal);
        initComponents();

        this.perfil = perfil;

        lblPerfil.setText("Para el Perfil: " + this.perfil.getNombre());

        mostrarGraficoTorta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();
        jPanelLienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estado de Mis Libros");

        lblPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfil.setText("Para el perfil: ");

        javax.swing.GroupLayout jPanelLienzoLayout = new javax.swing.GroupLayout(jPanelLienzo);
        jPanelLienzo.setLayout(jPanelLienzoLayout);
        jPanelLienzoLayout.setHorizontalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanelLienzoLayout.setVerticalGroup(
            jPanelLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEstadisticaEstadoDeMisLibros dialog = new JDialogEstadisticaEstadoDeMisLibros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void mostrarGraficoTorta() {

        List<Lectura> lecturaLibrosNoLeido = lecturaUtilImpl.getListadoLibrosPorLeerPorPerfil(perfil.getId());
        List<Lectura> lecturaLibrosTerminados = lecturaUtilImpl.getListadoLibrosTerminadosPorPerfil(perfil.getId());

        int cantidadLibrosNoLeidos = lecturaLibrosNoLeido.size();
        int cantidadLibrosTerminados = lecturaLibrosTerminados.size();

        // 1. Crear un Dataset simple para el gráfico de torta con datos de ejemplo
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Libros Terminados", cantidadLibrosTerminados);
        dataset.setValue("Libros en Lectura", cantidadLibrosNoLeidos);

        // 2. Crear el objeto JFreeChart (gráfico de torta)
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Estado de Mis Libros", // Título del gráfico
                dataset, // El dataset
                true, // ¿Mostrar leyenda?
                true, // ¿Mostrar tooltips?
                false // ¿Generar URLs?
        );

        // 3. (Opcional pero muy recomendado) Aplicar Anti-Aliasing para mejor calidad
        pieChart.setTextAntiAlias(true);
        pieChart.setRenderingHints(new RenderingHints(
                RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON
        ));
        pieChart.setRenderingHints(new RenderingHints(
                RenderingHints.KEY_TEXT_ANTIALIASING,
                RenderingHints.VALUE_TEXT_ANTIALIAS_ON
        ));

        // 4. Crear el ChartPanel para mostrar el gráfico en el panel
        ChartPanel chartPanel = new ChartPanel(pieChart);
        // Puedes establecer un tamaño preferido si lo deseas, pero BorderLayout lo expandirá
        // chartPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        // 5. Limpiar jPanelLienzo y añadir el nuevo ChartPanel
        jPanelLienzo.removeAll(); // Elimina cualquier componente anterior (gráfico, etc.)
        jPanelLienzo.setLayout(new BorderLayout()); // Asegura que jPanelLienzo use BorderLayout
        // para que el ChartPanel ocupe todo el espacio.
        // Es crucial si NetBeans lo tiene en GroupLayout por defecto.
        jPanelLienzo.add(chartPanel, BorderLayout.CENTER); // Añade el ChartPanel al centro

        // 6. Pedir a Swing que revalide y repinte el panel para que los cambios se muestren
        jPanelLienzo.revalidate(); // Le dice al layout manager que recalcule el tamaño de sus componentes
        jPanelLienzo.repaint();    // Le pide al componente que se redibuje a sí mismo

    }

//    private void mostrarGraficoDeLineas() {
//        // Obtener el ChartPanel con el gráfico
//        ChartPanel nuevoGraficoPanel = crearSimpleLineChart();
//
//        // 1. Limpiar el jPanelLienzo de cualquier componente anterior
//        jPanelLienzo.removeAll();
//
//        // 2. Establecer un Layout Manager adecuado para jPanelLienzo
//        // El código generado por el editor utiliza GroupLayout para jPanelLienzo.
//        // Para que el ChartPanel se expanda, es mejor establecer BorderLayout.
//        jPanelLienzo.setLayout(new BorderLayout());
//
//        // 3. Añadir el nuevo ChartPanel al jPanelLienzo
//        jPanelLienzo.add(nuevoGraficoPanel, BorderLayout.CENTER);
//
//        // 4. Pedir a Swing que revalide y repinte el panel para que los cambios se muestren
//        jPanelLienzo.revalidate();
//        jPanelLienzo.repaint();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JPanel jPanelLienzo;
    private javax.swing.JLabel lblPerfil;
    // End of variables declaration//GEN-END:variables
}
