/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gustavo.guardarlibros.vista;

import com.gustavo.guardarlibros.modelo.Estado;
import com.gustavo.guardarlibros.modelo.Lectura;
import com.gustavo.guardarlibros.modelo.Libro;
import com.gustavo.guardarlibros.modelo.Perfil;
import com.gustavo.guardarlibros.utils.LecturaUtilImpl;
import com.gustavo.guardarlibros.utils.LibroUtilImpl;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class JDialogEliminarLibro extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEliminarLibro.class.getName());

    private Perfil perfilSeleccionado;
    private Libro libroSeleccionado;

    private LecturaUtilImpl lecturaUtilImpl = new LecturaUtilImpl();
    private LibroUtilImpl libroUtilImpl = new LibroUtilImpl();

    /**
     * Creates new form JDialogEliminarLecturasDeLibroTerminado
     */
    public JDialogEliminarLibro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogEliminarLibro(java.awt.Frame parent, boolean modal, Perfil perfilSeleccionado, Libro libroSeleccionado) {
        super(parent, modal);
        initComponents();
        this.perfilSeleccionado = perfilSeleccionado;
        this.libroSeleccionado = libroSeleccionado;

        cargarElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaLecturas = new javax.swing.JList<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Libro");

        txtTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Eliminar Libro");

        jScrollPane1.setViewportView(listaLecturas);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aceptar-32.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtInfo.setAutoscrolls(true);

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        // 1. Define el mensaje y el título del diálogo
        String mensaje = "¿Estás seguro?";
        String titulo = "Confirmación";

        // 2. Muestra el diálogo y guarda la respuesta
        int resultado = JOptionPane.showConfirmDialog(this, mensaje, titulo, JOptionPane.YES_NO_OPTION);

        // 3. Evalúa la respuesta del usuario
        if (resultado == JOptionPane.YES_OPTION) {
            // El usuario hizo clic en "Sí"

            if (perfilSeleccionado != null && libroSeleccionado != null) {

                lecturaUtilImpl.eliminarLecturasPorLibro(libroSeleccionado);
                libroUtilImpl.eliminarLibro(libroSeleccionado);

                JOptionPane.showMessageDialog(this, "Acaba de Eliminar el libro junto a todas sus Lecturas.", "Información", JOptionPane.INFORMATION_MESSAGE);

                this.dispose();

            } else {
                System.out.println("Libro o perfil son null.");
            }

        } else {
            // El usuario hizo clic en "No" o cerró el diálogo
            System.out.println("El usuario dijo NO o cerró el diálogo.");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cargarElementos() {

        List<Lectura> lecturasAEliminar = lecturaUtilImpl.getListadoLibrosEnLecturaPorPerfilYLibro(perfilSeleccionado.getId(), libroSeleccionado);

        int cantidadLecturas = 0;
        String nombreLibro = "";
        String autor = "";

        nombreLibro = libroSeleccionado.getNombre().trim().toUpperCase();
        autor = libroSeleccionado.getAutor().trim().toUpperCase();
        cantidadLecturas = lecturasAEliminar.size();

        String[] contenidoDeLaLista = lecturasAEliminar.stream()
                .map(this::formatearLecturaParaLista)
                .toArray((i) -> new String[i]);

        String mensajeInfo = "<html>Las siguientes <b>" + cantidadLecturas
                + "</b> lecturas serán eliminadas.<br>"
                + "El libro <b>'" + nombreLibro
                + "'</b> de <b>" + autor + "</b> también será eliminado.<br>"
                + "Perderás todo tu progreso.</html>";

        txtInfo.setText(mensajeInfo);

        listaLecturas.setListData(contenidoDeLaLista);
    }

    private String formatearLecturaParaLista(Lectura lectura) {
        // Opción 1: Un formato más condensado y con comas/guiones
        // Ejemplo: "Libro: El Quijote (Cervantes) - Pág: 123, Mins: 45, Inicio: 01/01/2023 (Total: 800)"
//        return String.format("Libro: %s (%s) - Pág: %d, Mins: %d, Inicio: %s (Total: %d)",
//                lectura.getLibro().getNombre(),
//                lectura.getLibro().getAutor(),
//                lectura.getPaginaActual(),
//                lectura.getMinutosLeidos(),
//                // Asegúrate que getFechaInicio() devuelve un String formateado
//                // O formatéalo aquí si es un Date: new SimpleDateFormat("dd/MM/yyyy").format(lectura.getFechaInicio())
//                lectura.getFechaInicio(),
//                lectura.getLibro().getCantidadPaginas());

        /*
    // Opción 2: Si el espacio es muy limitado, enfócate en lo más relevante
    // Ejemplo: "El Quijote (Cervantes) - Pág. 123 de 800"
    return String.format("%s (%s) - Pág. %d de %d",
            lectura.getLibro().getNombre(),
            lectura.getLibro().getAutor(),
            lectura.getPaginaActual(),
            lectura.getLibro().getCantidadPaginas());
         */
        // Opción 3: Incluir fecha y minutos de forma más breve
        // Ejemplo: "El Quijote (Cervantes) - Pág. 123 (45min, 01/01/2023)"
        return String.format("%s (%s) - Pág. %d de %d (%dmin, %s)",
                lectura.getLibro().getNombre(),
                lectura.getLibro().getAutor(),
                lectura.getPaginaActual(),
                lectura.getLibro().getCantidadPaginas(),
                lectura.getMinutosLeidos(),
                lectura.getFechaInicio());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEliminarLibro dialog = new JDialogEliminarLibro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaLecturas;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
