/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gustavo.guardarlibros.vista;

import com.gustavo.guardarlibros.modelo.Estado;
import com.gustavo.guardarlibros.modelo.Lectura;
import com.gustavo.guardarlibros.modelo.Libro;
import com.gustavo.guardarlibros.modelo.Perfil;
import com.gustavo.guardarlibros.utils.LecturaUtilImpl;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class JDialogEditarLectura extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogEditarLectura.class.getName());

    private LecturaUtilImpl lecturaUtilImpl = new LecturaUtilImpl();

    private Libro libro = new Libro();
    private Perfil perfil = new Perfil();
    private Lectura lectura = new Lectura();
    private Lectura lecturaLibroNoLeido = new Lectura();

    /**
     * Creates new form JDialogAgregarLectura
     */
    public JDialogEditarLectura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public JDialogEditarLectura(java.awt.Frame parent, boolean modal, Lectura lectura, Perfil perfil, Lectura lecturaLibroNoLeido) {
        super(parent, modal);
        initComponents();

        this.libro = lectura.getLibro();
        this.perfil = perfil;
        this.lectura = lectura;
        this.lecturaLibroNoLeido = lecturaLibroNoLeido;

        LocalDate fechaActual = LocalDate.now();

        txtFecha.setText(fechaActual.toString());
        txtLibro.setText(libro.getNombre() + " de " + libro.getAutor());
        txtPerfil.setText(perfil.getNombre());
        lblPagina.setText("Pagina (Total " + this.libro.getCantidadPaginas() + ")" + ":");
        txtPagina.setText(String.valueOf(lectura.getPaginaActual()));
        txtFecha.setText(String.valueOf(lectura.getFechaInicio()));
        txtTiempo.setText(this.lectura.getMinutosLeidos().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelParaBoton = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        panelParaDatos = new javax.swing.JPanel();
        lblLibro = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        lblPerfil = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JTextField();
        lblPagina = new javax.swing.JLabel();
        txtPagina = new javax.swing.JFormattedTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        lblTiempo = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar nueva lectura");

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Datos de la Lectura");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParaBotonLayout = new javax.swing.GroupLayout(panelParaBoton);
        panelParaBoton.setLayout(panelParaBotonLayout);
        panelParaBotonLayout.setHorizontalGroup(
            panelParaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParaBotonLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelParaBotonLayout.setVerticalGroup(
            panelParaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParaBotonLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelParaBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblLibro.setText("Libro:");
        lblLibro.setToolTipText("Libro en lectra, ya previamente seleccionado.");

        txtLibro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtLibro.setToolTipText("Libro en lectra, ya previamente seleccionado.");
        txtLibro.setEnabled(false);

        lblPerfil.setText("Perfil:");
        lblPerfil.setToolTipText("Perfil de lectura, ya previamente seleccionado.");

        txtPerfil.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtPerfil.setToolTipText("Perfil de lectura, ya previamente seleccionado.");
        txtPerfil.setEnabled(false);

        lblPagina.setText("Pagina:");
        lblPagina.setToolTipText("Debe ingresar la pagina donde se quedo al finalizar el tiempo de lectura.");

        txtPagina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#")) {
            // Bloque de inicialización de instancia para configurar el NumberFormatter
            {
                setMinimum(1); // O 1 si quieres estrictamente positivos (>0)
                setMaximum(null); // Sin límite superior
                setAllowsInvalid(false);
                setOverwriteMode(true);
                ((java.text.DecimalFormat) getFormat()).setParseIntegerOnly(true);
                setCommitsOnValidEdit(true); // Ayuda a que el valor se actualice más rápido
            }

            @Override
            public Object stringToValue(String text) throws java.text.ParseException {
                if (text == null || text.trim().isEmpty()) {
                    return null; // Si el texto está vacío, devuelve null
                }
                // Si no está vacío, usa el comportamiento por defecto del NumberFormatter
                return super.stringToValue(text);
            }

            // Opcional: Esto ayuda a que el campo muestre vacío si su valor es null
            @Override
            public String valueToString(Object value) throws java.text.ParseException {
                if (value == null) {
                    return ""; // Si el valor es null, muestra una cadena vacía
                }
                return super.valueToString(value);
            }
        }));
        txtPagina.setToolTipText("Debe ingresar la pagina donde se quedo al finalizar el tiempo de lectura.");

        lblFecha.setText("Fecha:");
        lblFecha.setToolTipText("Debe ingresar una fecha con el siguente formato AAAA-MM-DD. Ej. 2024-06-12");

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txtFecha.setToolTipText("Debe ingresar una fecha con el siguente formato AAAA-MM-DD. Ej. 2024-06-12");

        lblTiempo.setText("Tiempo (min):");
        lblTiempo.setToolTipText("Tiempo en minutos de la sesión de lectura.");

        txtTiempo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#")) {
            // Bloque de inicialización de instancia para configurar el NumberFormatter
            {
                setMinimum(1); // O 1 si quieres estrictamente positivos (>0)
                setMaximum(null); // Sin límite superior
                setAllowsInvalid(false);
                setOverwriteMode(true);
                ((java.text.DecimalFormat) getFormat()).setParseIntegerOnly(true);
                setCommitsOnValidEdit(true); // Ayuda a que el valor se actualice más rápido
            }

            @Override
            public Object stringToValue(String text) throws java.text.ParseException {
                if (text == null || text.trim().isEmpty()) {
                    return null; // Si el texto está vacío, devuelve null
                }
                // Si no está vacío, usa el comportamiento por defecto del NumberFormatter
                return super.stringToValue(text);
            }

            // Opcional: Esto ayuda a que el campo muestre vacío si su valor es null
            @Override
            public String valueToString(Object value) throws java.text.ParseException {
                if (value == null) {
                    return ""; // Si el valor es null, muestra una cadena vacía
                }
                return super.valueToString(value);
            }
        }));
        txtTiempo.setToolTipText("Tiempo en minutos de la sesión de lectura.");

        javax.swing.GroupLayout panelParaDatosLayout = new javax.swing.GroupLayout(panelParaDatos);
        panelParaDatos.setLayout(panelParaDatosLayout);
        panelParaDatosLayout.setHorizontalGroup(
            panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParaDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPagina)
                    .addComponent(lblFecha)
                    .addComponent(lblPerfil)
                    .addComponent(lblLibro)
                    .addComponent(lblTiempo))
                .addGap(18, 18, 18)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(txtLibro)
                    .addComponent(txtPerfil)
                    .addComponent(txtPagina)
                    .addComponent(txtFecha))
                .addContainerGap())
        );
        panelParaDatosLayout.setVerticalGroup(
            panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParaDatosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibro)
                    .addComponent(txtLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerfil)
                    .addComponent(txtPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagina)
                    .addComponent(txtPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelParaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempo)
                    .addComponent(txtTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelParaBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelParaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelParaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panelParaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtPagina.setText("");
        txtFecha.setText("");
        txtTiempo.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        boolean sePuedeGuardar = !txtLibro.getText().isEmpty() && !txtPerfil.getText().isEmpty() && !txtFecha.getText().isEmpty() && !txtTiempo.getText().isEmpty() && !txtPagina.getText().isEmpty();

        if (sePuedeGuardar) {

            Integer paginaFinalLibro = libro.getCantidadPaginas();

            Integer paginaAGuardar = Integer.valueOf(txtPagina.getText());

            boolean esValidaLaPaginaIngresada = esValidaLaCantidadDePaginas(paginaAGuardar);
            boolean esLaPaginaIngresaLaUltimaDelLibro = paginaAGuardar.equals(paginaFinalLibro);

            boolean esValidaLaFechaAIngresar = esValidaLaFecha(LocalDate.parse(txtFecha.getText()));

            if (!LocalDate.parse(txtFecha.getText()).isAfter(LocalDate.now())) {
                if (esValidaLaFechaAIngresar) {
                    if (esValidaLaPaginaIngresada) {

                        Lectura nuevaLectura = new Lectura();

                        if (esLaPaginaIngresaLaUltimaDelLibro) {

                            nuevaLectura.setId(lectura.getId());
                            nuevaLectura.setLibro(libro);
                            nuevaLectura.setPerfil(perfil);
                            nuevaLectura.setFechaInicio(LocalDate.parse(txtFecha.getText()));
                            nuevaLectura.setMinutosLeidos(Integer.valueOf(txtTiempo.getText()));
                            nuevaLectura.setPaginaActual(Integer.valueOf(txtPagina.getText()));
                            nuevaLectura.setEstado(Estado.LEYENDO);

                            lecturaUtilImpl.editarUnaLectura(nuevaLectura);

                            //ACA DEBO MODIFICAR LA LECTURA QUE ESTA EN ESTADO DE NO_LEIDO Y PASARLO A TERMINADO, LA LECUTRA ES LA DE LIBRO NO LEDIO(SI NO, NO FUNCIONA)
                            lecturaUtilImpl.actualizarEstadoYFechaDeUnaLectura(lecturaLibroNoLeido, Estado.TERMINADO);

                            JOptionPane.showMessageDialog(this, "Acaba de ingresar la ultima pagina del libro. Su libro pasara a la lista de Libros terminados.", "Información", JOptionPane.INFORMATION_MESSAGE);

                            this.dispose();
                        } else {

                            nuevaLectura.setId(lectura.getId());
                            nuevaLectura.setLibro(libro);
                            nuevaLectura.setPerfil(perfil);
                            nuevaLectura.setFechaInicio(LocalDate.parse(txtFecha.getText()));
                            nuevaLectura.setMinutosLeidos(Integer.valueOf(txtTiempo.getText()));
                            nuevaLectura.setPaginaActual(Integer.valueOf(txtPagina.getText()));
                            nuevaLectura.setEstado(Estado.LEYENDO);

                            lecturaUtilImpl.editarUnaLectura(nuevaLectura);

                            JOptionPane.showMessageDialog(this, "Se Edito la lectura.", "Exito", JOptionPane.INFORMATION_MESSAGE);

                            this.dispose();
                        }

                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private boolean esValidaLaFecha(LocalDate fechaAIngresar) {

        List<Lectura> listaDeLecturas = lecturaUtilImpl.getListadoLibrosEnLecturaPorPerfilYLibro(perfil.getId(), libro);

        if (!listaDeLecturas.isEmpty()) {
            Lectura actual = null;
            Lectura siguiente = null;
            Lectura anterior = null;

            for (int i = 0; i < listaDeLecturas.size(); i++) {
                if (listaDeLecturas.get(i).equals(lectura)) {

                    actual = listaDeLecturas.get(i);

                    try {
                        siguiente = listaDeLecturas.get(i + 1);
                    } catch (IndexOutOfBoundsException e) {
                        siguiente = null;
                    }

                    try {
                        anterior = listaDeLecturas.get(i - 1);
                    } catch (IndexOutOfBoundsException e) {
                        anterior = null;
                    }

                    break;
                }
            }

            if (actual != null) {
                // Validación de la fecha actual: debe ser anterior o igual a hoy
                if (LocalDate.parse(txtFecha.getText()).isBefore(LocalDate.now()) || LocalDate.parse(txtFecha.getText()).isEqual(LocalDate.now())) {
                    // Si hay dos elementos y el que se quiere editar es el primero
                    if (anterior == null && siguiente != null) {
                        if (fechaAIngresar.isAfter(siguiente.getFechaInicio())) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La fecha debe ser posterior a la fecha de la siguiente lectura en la lista.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Si hay dos elementos, pero el elemento a editar es el ultimo
                    } else if (anterior != null && siguiente == null) {
                        if (fechaAIngresar.isBefore(anterior.getFechaInicio())) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La fecha debe ser anterior a la fecha de la lectura previa en la lista.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Cuando hay solo un elemento
                    } else if (anterior == null && siguiente == null) {
                        if (fechaAIngresar.isBefore(LocalDate.now()) || fechaAIngresar.isEqual(LocalDate.now())) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La fecha debe ser igual o anterior a la fecha actual.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Hay 3 elementos y el elemento a editar es el del medio
                    } else if (anterior != null && siguiente != null) {
                        if (fechaAIngresar.isBefore(anterior.getFechaInicio()) && fechaAIngresar.isAfter(siguiente.getFechaInicio())) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La fecha debe estar entre la lectura anterior y la siguiente.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } else {
                    // Mensaje si la fecha parseada de txtFecha.getText() es futura
                    JOptionPane.showMessageDialog(null, "La fecha ingresada no puede ser una fecha futura.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
                }
                return false; // Retorna false si ninguna de las condiciones de arriba retornó true
            } else {
                // Mensaje si la lectura actual no se encontró en la lista
                JOptionPane.showMessageDialog(null, "La lectura que intenta editar no fue encontrada en la lista.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {

            JOptionPane.showMessageDialog(null, "No hay lecturas registradas. La fecha debe ser igual o anterior a la fecha actual.", "Fecha Inválida", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private boolean esValidaLaCantidadDePaginas(Integer paginaAIngresar) {

        List<Lectura> listaDeLecturas = lecturaUtilImpl.getListadoLibrosEnLecturaPorPerfilYLibro(perfil.getId(), libro);

        if (!listaDeLecturas.isEmpty()) {
            Lectura actual = null;
            Lectura siguiente = null;
            Lectura anterior = null;

            for (int i = 0; i < listaDeLecturas.size(); i++) {
                if (listaDeLecturas.get(i).equals(lectura)) {

                    actual = listaDeLecturas.get(i);

                    try {
                        siguiente = listaDeLecturas.get(i + 1);
                    } catch (IndexOutOfBoundsException e) {
                        siguiente = null;
                    }

                    try {
                        anterior = listaDeLecturas.get(i - 1);
                    } catch (IndexOutOfBoundsException e) {
                        anterior = null;
                    }

                    break;
                }
            }

            if (actual != null) {
                // Validación de la pagina actual: debe ser mayor a cero && menor o igual al total del paginas del libro
                if (Integer.parseInt(txtPagina.getText()) > 0 && Integer.valueOf(txtPagina.getText()) <= libro.getCantidadPaginas()) {
                    // Si hay dos elementos y el que se quiere editar es el primero
                    if (anterior == null && siguiente != null) {
                        if (Integer.valueOf(txtPagina.getText()) > siguiente.getPaginaActual()) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La página debe ser mayor que la pagina de lectura anterior.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Si hay dos elementos, pero el elemento a editar es el ultimo
                    } else if (anterior != null && siguiente == null) {
                        if (Integer.valueOf(txtPagina.getText()) < anterior.getPaginaActual()) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La página deber ser menor que la cantidad de paginas de la anterior lectura.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Cuando hay solo un elemento
                    } else if (anterior == null && siguiente == null) {
                        if (Integer.parseInt(txtPagina.getText()) > 0 && Integer.valueOf(txtPagina.getText()) <= libro.getCantidadPaginas()) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La página debe ser mayor a cero y menor o igual a el total de páginas del libro.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
                        }

                        // Hay 3 elementos y el elemento a editar es el del medio
                    } else if (anterior != null && siguiente != null) {
                        if (Integer.valueOf(txtPagina.getText()) < anterior.getPaginaActual() && Integer.valueOf(txtPagina.getText()) > siguiente.getPaginaActual()) {
                            return true;
                        } else {
                            JOptionPane.showMessageDialog(null, "La Página deber estar entre la cantidad de paginas de las lectura anterior y siguiente.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                } else {
                    // Mensaje si la fecha parseada de txtFecha.getText() es futura
                    JOptionPane.showMessageDialog(null, "La pagaina ingresada no puede ser mayor al total de paginas del libro o menor a cero.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
                }
                return false; // Retorna false si ninguna de las condiciones de arriba retornó true
            } else {
                // Mensaje si la lectura actual no se encontró en la lista
                JOptionPane.showMessageDialog(null, "La lectura que intenta editar no fue encontrada en la lista.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {

            JOptionPane.showMessageDialog(null, "No hay lecturas registradas.", "Página Inválida", JOptionPane.ERROR_MESSAGE);
            return false;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDialogEditarLectura dialog = new JDialogEditarLectura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelParaBoton;
    private javax.swing.JPanel panelParaDatos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JFormattedTextField txtPagina;
    private javax.swing.JTextField txtPerfil;
    private javax.swing.JFormattedTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
