/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.gustavo.guardarlibros.vista;

import java.awt.BorderLayout;
import java.awt.EventQueue;
import java.awt.Font;
import javax.swing.JEditorPane;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author gusta
 */
public class JDialogAcercaDe extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDialogAcercaDe.class.getName());

    private JTextArea textArea;
    private JScrollPane scrollPane;

    /**
     * Creates new form JDialogAcercaDe
     */
    public JDialogAcercaDe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarAcercaDe();  // método personalizado
        setLocationRelativeTo(parent);
    }

    /**
     * Método personalizado para agregar contenido a la ventana
     */
    private void configurarAcercaDe() {
        setTitle("Acerca de GuardarLibros");
        setSize(500, 350);
        setResizable(false);
        getContentPane().setLayout(new BorderLayout());

        String html = """
        <html>
        <body style='font-family:Segoe UI; font-size:12px; padding:10px;'>
            <h2 style='margin-top: 0;'>Gestión de Libros</h2>
            <p><b>Versión:</b> 1.0 – Agosto 2025</p>

            <p><b>Descripción:</b><br>
            Aplicación de escritorio para gestionar tu biblioteca personal.<br>
            Agregá libros, registrá tus sesiones de lectura, y llevá un control del estado de lectura (terminado o no terminado).</p>

            <p><b>Autor:</b> Gustavo Francisco Silva Artaza<br>
            <b>GitHub:</b> <a href='https://github.com/gustavo4456'>https://github.com/gustavo4456</a></p>

            <p><b>Tecnología:</b> Java + Swing<br>
            <b>Licencia:</b> Uso personal y educativo</p>

            <p><i>Gracias por usar Gestión de Libros 📚</i></p>
        </body>
        </html>
        """;

        JEditorPane editorPane = new JEditorPane("text/html", html);
        editorPane.setEditable(false);
        editorPane.setOpaque(false);
        editorPane.setBorder(null);

        JScrollPane scrollPane = new JScrollPane(editorPane);
        scrollPane.setBorder(null);
        scrollPane.setViewportBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);

        getContentPane().add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        EventQueue.invokeLater(() -> {
            JDialogAcercaDe dialog = new JDialogAcercaDe(new JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
