/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gustavo.guardarlibros.vista;

import com.gustavo.guardarlibros.modelo.Lectura;
import com.gustavo.guardarlibros.modelo.Perfil;
import com.gustavo.guardarlibros.utils.LecturaUtilImpl;
import com.gustavo.guardarlibros.utils.PerfilUtilImpl;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class JfPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JfPrincipal.class.getName());

    private LecturaUtilImpl lecturaUtilImpl = new LecturaUtilImpl();
    private PerfilUtilImpl perfilUtil = new PerfilUtilImpl();

    private Lectura libroLecturaSeleccionada;
    private Lectura libroLecturaTerminadasSeleccionada;
    private Lectura libroEnEstadoLeyendoSeleccionada; //tabla del medio
    private Perfil perfilSeleccionado;

    /**
     * Creates new form JfPrincipal
     */
    public JfPrincipal() {
        initComponents();
        cargarElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grillaLibrosPorLeer1 = new com.gustavo.guardarlibros.vista.grillas.GrillaLibrosPorLeer();
        grillaLibrosTerminados1 = new com.gustavo.guardarlibros.vista.grillas.GrillaLibrosTerminados();
        grillaLibrosEnLectura1 = new com.gustavo.guardarlibros.vista.grillas.GrillaLibrosEnLectura();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelPerfil = new javax.swing.JPanel();
        cbPerfil = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        jPanelLibrosPorLeer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbLibros = new javax.swing.JTable();
        jPanelEnLectura = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbLectura = new javax.swing.JTable();
        jPaneLibrosTerminados = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbLibrosTerminados = new javax.swing.JTable();
        jPaneLeerAEnLectura = new javax.swing.JPanel();
        jPanelInternoDeLeerAEnLectura = new javax.swing.JPanel();
        btnAgregarLectura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEditarLectura = new javax.swing.JButton();
        jPanelEnLecturaATerminados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminarLibroTerminado = new javax.swing.JButton();
        btnEditarLecturaLibroTerminado = new javax.swing.JButton();
        jMenuBarra = new javax.swing.JMenuBar();
        jMenuNuevo = new javax.swing.JMenu();
        jItemNuevoLibro = new javax.swing.JMenuItem();
        jItemNuevoPerfil = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jItemMenuEditarLibro = new javax.swing.JMenuItem();
        jItemMenuEditarPerfil = new javax.swing.JMenuItem();
        jMenuEstadisticas = new javax.swing.JMenu();
        jItemEstadisticaProgresoPorLibro = new javax.swing.JMenuItem();
        jItemEstadisticaActividadDeLectura = new javax.swing.JMenuItem();
        jItemEstadisticaEstadoDeMisLibros = new javax.swing.JMenuItem();
        jItemEstadisticaLecturasPorAutor = new javax.swing.JMenuItem();
        jItemPaginasPorMinuto = new javax.swing.JMenuItem();
        jItemLecturasPorPeriodo = new javax.swing.JMenuItem();
        jItemResumenGeneral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de libros");

        jPanelPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder("Selección del perfil"));

        cbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerfilActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addContainerGap())
        );

        jPanelLibrosPorLeer.setBorder(javax.swing.BorderFactory.createTitledBorder("Libros por leer"));

        tbLibros.setModel(grillaLibrosPorLeer1);
        tbLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLibros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLibrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbLibros);

        javax.swing.GroupLayout jPanelLibrosPorLeerLayout = new javax.swing.GroupLayout(jPanelLibrosPorLeer);
        jPanelLibrosPorLeer.setLayout(jPanelLibrosPorLeerLayout);
        jPanelLibrosPorLeerLayout.setHorizontalGroup(
            jPanelLibrosPorLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLibrosPorLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLibrosPorLeerLayout.setVerticalGroup(
            jPanelLibrosPorLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLibrosPorLeerLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jPanelEnLectura.setBorder(javax.swing.BorderFactory.createTitledBorder("En Lectura"));

        tbLectura.setModel(grillaLibrosEnLectura1);
        tbLectura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLectura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tbLectura);

        javax.swing.GroupLayout jPanelEnLecturaLayout = new javax.swing.GroupLayout(jPanelEnLectura);
        jPanelEnLectura.setLayout(jPanelEnLecturaLayout);
        jPanelEnLecturaLayout.setHorizontalGroup(
            jPanelEnLecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnLecturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEnLecturaLayout.setVerticalGroup(
            jPanelEnLecturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnLecturaLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPaneLibrosTerminados.setBorder(javax.swing.BorderFactory.createTitledBorder("Libros terminados"));

        tbLibrosTerminados.setModel(grillaLibrosTerminados1);
        tbLibrosTerminados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLibrosTerminados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLibrosTerminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLibrosTerminadosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbLibrosTerminados);

        javax.swing.GroupLayout jPaneLibrosTerminadosLayout = new javax.swing.GroupLayout(jPaneLibrosTerminados);
        jPaneLibrosTerminados.setLayout(jPaneLibrosTerminadosLayout);
        jPaneLibrosTerminadosLayout.setHorizontalGroup(
            jPaneLibrosTerminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLibrosTerminadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPaneLibrosTerminadosLayout.setVerticalGroup(
            jPaneLibrosTerminadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneLibrosTerminadosLayout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jPaneLeerAEnLectura.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones para Libros no terminados"));
        jPaneLeerAEnLectura.setLayout(new java.awt.GridBagLayout());

        jPanelInternoDeLeerAEnLectura.setLayout(new javax.swing.BoxLayout(jPanelInternoDeLeerAEnLectura, javax.swing.BoxLayout.Y_AXIS));

        btnAgregarLectura.setText("Agregar --->");
        btnAgregarLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLecturaActionPerformed(evt);
            }
        });
        jPanelInternoDeLeerAEnLectura.add(btnAgregarLectura);

        jLabel1.setMaximumSize(new java.awt.Dimension(0, 4));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 4));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanelInternoDeLeerAEnLectura.add(jLabel1);

        btnEditarLectura.setText("Editar Lectura");
        btnEditarLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLecturaActionPerformed(evt);
            }
        });
        jPanelInternoDeLeerAEnLectura.add(btnEditarLectura);

        jPaneLeerAEnLectura.add(jPanelInternoDeLeerAEnLectura, new java.awt.GridBagConstraints());

        jPanelEnLecturaATerminados.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones para libros terminados"));
        jPanelEnLecturaATerminados.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel2.setMaximumSize(new java.awt.Dimension(0, 4));
        jLabel2.setMinimumSize(new java.awt.Dimension(0, 4));
        jLabel2.setName(""); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanel1.add(jLabel2);

        btnEliminarLibroTerminado.setText("<---Eliminar");
        btnEliminarLibroTerminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroTerminadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarLibroTerminado);

        btnEditarLecturaLibroTerminado.setText("Editar Lectura");
        btnEditarLecturaLibroTerminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLecturaLibroTerminadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarLecturaLibroTerminado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(135, 6, 161, 6);
        jPanelEnLecturaATerminados.add(jPanel1, gridBagConstraints);

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanelLibrosPorLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPaneLeerAEnLectura, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelEnLectura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelEnLecturaATerminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPaneLibrosTerminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelEnLectura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneLeerAEnLectura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLibrosPorLeer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPaneLibrosTerminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEnLecturaATerminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuNuevo.setText("Nuevo");

        jItemNuevoLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItemNuevoLibro.setText("Libro");
        jItemNuevoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemNuevoLibroActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jItemNuevoLibro);

        jItemNuevoPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItemNuevoPerfil.setText("Perfil");
        jItemNuevoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemNuevoPerfilActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jItemNuevoPerfil);

        jMenuBarra.add(jMenuNuevo);

        jMenuEditar.setText("Editar");

        jItemMenuEditarLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jItemMenuEditarLibro.setText("Libro");
        jMenuEditar.add(jItemMenuEditarLibro);

        jItemMenuEditarPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jItemMenuEditarPerfil.setText("Perfil");
        jItemMenuEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemMenuEditarPerfilActionPerformed(evt);
            }
        });
        jMenuEditar.add(jItemMenuEditarPerfil);

        jMenuBarra.add(jMenuEditar);

        jMenuEstadisticas.setText("Estadisticas");

        jItemEstadisticaProgresoPorLibro.setText("Progreso por Libro");
        jItemEstadisticaProgresoPorLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEstadisticaProgresoPorLibroActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemEstadisticaProgresoPorLibro);

        jItemEstadisticaActividadDeLectura.setText("Actividad de Lectura");
        jItemEstadisticaActividadDeLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEstadisticaActividadDeLecturaActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemEstadisticaActividadDeLectura);

        jItemEstadisticaEstadoDeMisLibros.setText("Estado de Mis Libros");
        jItemEstadisticaEstadoDeMisLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEstadisticaEstadoDeMisLibrosActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemEstadisticaEstadoDeMisLibros);

        jItemEstadisticaLecturasPorAutor.setText("Lecturas por Autor");
        jItemEstadisticaLecturasPorAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEstadisticaLecturasPorAutorActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemEstadisticaLecturasPorAutor);

        jItemPaginasPorMinuto.setText("Páginas por Minuto");
        jItemPaginasPorMinuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemPaginasPorMinutoActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemPaginasPorMinuto);

        jItemLecturasPorPeriodo.setText("Lecturas por Periodo");
        jItemLecturasPorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemLecturasPorPeriodoActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemLecturasPorPeriodo);

        jItemResumenGeneral.setText("Resumen General");
        jItemResumenGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemResumenGeneralActionPerformed(evt);
            }
        });
        jMenuEstadisticas.add(jItemResumenGeneral);

        jMenuBarra.add(jMenuEstadisticas);

        setJMenuBar(jMenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jItemNuevoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemNuevoLibroActionPerformed
        // TODO add your handling code here:
        JDialogAgregarLibro jDialogAgregarLibro = new JDialogAgregarLibro(this, rootPaneCheckingEnabled);
        jDialogAgregarLibro.setVisible(true);
    }//GEN-LAST:event_jItemNuevoLibroActionPerformed

    private void jItemNuevoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemNuevoPerfilActionPerformed
        // TODO add your handling code here:
        JDialogAgregarPerfil jDialogAgregarPerfil = new JDialogAgregarPerfil(this, rootPaneCheckingEnabled);
        jDialogAgregarPerfil.setVisible(true);
    }//GEN-LAST:event_jItemNuevoPerfilActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        cargarElementos();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerfilActionPerformed
        // TODO add your handling code here:

        cargarElementos();
        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();
    }//GEN-LAST:event_cbPerfilActionPerformed

    private void tbLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLibrosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tbLibros.getSelectedRow();
        libroLecturaSeleccionada = grillaLibrosPorLeer1.getLectura(filaSeleccionada);

        cargarTablaLibrosEnLectura();

        // System.out.println("LECTURA SELECCIONADA: " + libroLecturaSeleccionada);
    }//GEN-LAST:event_tbLibrosMouseClicked

    private void btnAgregarLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLecturaActionPerformed
        // TODO add your handling code here:

        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

        if (tbLibros.getSelectedRow() != -1) {
            libroLecturaSeleccionada = grillaLibrosPorLeer1.getLectura(tbLibros.getSelectedRow());
        }

        if (perfilSeleccionado != null && libroLecturaSeleccionada != null) {
            JDialogAgregarLectura agregarLectura = new JDialogAgregarLectura(this, rootPaneCheckingEnabled, libroLecturaSeleccionada, perfilSeleccionado);
            agregarLectura.setVisible(true);
            cargarElementos();

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil y un libro.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_btnAgregarLecturaActionPerformed

    private void tbLibrosTerminadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLibrosTerminadosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tbLibrosTerminados.getSelectedRow();
        libroLecturaTerminadasSeleccionada = grillaLibrosTerminados1.getLectura(filaSeleccionada);

        cargarTablaLecturasDeLibrosTerminados();

        //System.out.println("LECTURA SELECCIONADA: " + libroLecturaTerminadasSeleccionada);
    }//GEN-LAST:event_tbLibrosTerminadosMouseClicked

    private void btnEliminarLibroTerminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroTerminadoActionPerformed
        // TODO add your handling code here:

        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

        if (tbLibrosTerminados.getSelectedRow() != -1) {
            libroLecturaTerminadasSeleccionada = grillaLibrosTerminados1.getLectura(tbLibrosTerminados.getSelectedRow());
        }

        if (perfilSeleccionado != null && libroLecturaTerminadasSeleccionada != null) {
            JDialogEliminarLecturasDeLibroTerminado jDialogEliminarLecturasDeLibroTerminado = new JDialogEliminarLecturasDeLibroTerminado(this, rootPaneCheckingEnabled, libroLecturaTerminadasSeleccionada, perfilSeleccionado);

            jDialogEliminarLecturasDeLibroTerminado.setVisible(true);

            cargarElementos();

            this.libroLecturaTerminadasSeleccionada = null;
            this.perfilSeleccionado = null;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil y un libro que haya terminado.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEliminarLibroTerminadoActionPerformed

    private void btnEditarLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLecturaActionPerformed
        // TODO add your handling code here:

        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

        if (tbLectura.getSelectedRow() != -1 && tbLibros.getSelectedRow() != -1) {
            libroEnEstadoLeyendoSeleccionada = grillaLibrosEnLectura1.getLectura(tbLectura.getSelectedRow());
            libroLecturaSeleccionada = grillaLibrosPorLeer1.getLectura(tbLibros.getSelectedRow());
        }

        if (perfilSeleccionado != null && libroEnEstadoLeyendoSeleccionada != null && libroLecturaSeleccionada != null) {
            JDialogEditarLectura editarLectura = new JDialogEditarLectura(this, rootPaneCheckingEnabled, libroEnEstadoLeyendoSeleccionada, perfilSeleccionado, libroLecturaSeleccionada);
            editarLectura.setVisible(true);
            cargarElementos();

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil, libro y una Lectura a editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEditarLecturaActionPerformed

    private void btnEditarLecturaLibroTerminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLecturaLibroTerminadoActionPerformed
        // TODO add your handling code here:
        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

        if (tbLectura.getSelectedRow() != -1 && tbLibrosTerminados.getSelectedRow() != -1) {
            libroEnEstadoLeyendoSeleccionada = grillaLibrosEnLectura1.getLectura(tbLectura.getSelectedRow());
            libroLecturaTerminadasSeleccionada = grillaLibrosTerminados1.getLectura(tbLibrosTerminados.getSelectedRow());
        }

        if (perfilSeleccionado != null && libroEnEstadoLeyendoSeleccionada != null && libroLecturaTerminadasSeleccionada != null) {
            JDialogEditarLecturaLibroTerminado editarLectura = new JDialogEditarLecturaLibroTerminado(this, rootPaneCheckingEnabled, libroEnEstadoLeyendoSeleccionada, perfilSeleccionado, libroLecturaTerminadasSeleccionada);
            editarLectura.setVisible(true);
            cargarElementos();

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil, libro terminado y una Lectura a editar.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnEditarLecturaLibroTerminadoActionPerformed

    private void jItemEstadisticaProgresoPorLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEstadisticaProgresoPorLibroActionPerformed
        // TODO add your handling code here:

        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaProgresoPorLibro jDialogEstadisticaProgresoPorLibro = new JDialogEstadisticaProgresoPorLibro(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaProgresoPorLibro.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_jItemEstadisticaProgresoPorLibroActionPerformed

    private void jItemEstadisticaActividadDeLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEstadisticaActividadDeLecturaActionPerformed
        // TODO add your handling code here:

        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaActividadLectura jDialogEstadisticaAvanceLectura = new JDialogEstadisticaActividadLectura(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaAvanceLectura.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemEstadisticaActividadDeLecturaActionPerformed

    private void jItemEstadisticaEstadoDeMisLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEstadisticaEstadoDeMisLibrosActionPerformed
        // TODO add your handling code here:
        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaEstadoDeMisLibros jDialogEstadisticaEstadoDeMisLibros = new JDialogEstadisticaEstadoDeMisLibros(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaEstadoDeMisLibros.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemEstadisticaEstadoDeMisLibrosActionPerformed

    private void jItemEstadisticaLecturasPorAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEstadisticaLecturasPorAutorActionPerformed
        // TODO add your handling code here:
        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaLecturaPorAutor jDialogEstadisticaLecturaPorAutor = new JDialogEstadisticaLecturaPorAutor(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaLecturaPorAutor.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemEstadisticaLecturasPorAutorActionPerformed

    private void jItemPaginasPorMinutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemPaginasPorMinutoActionPerformed
        // TODO add your handling code here:

        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaPaginaPorMinuto jDialogEstadisticaPaginaPorMinuto = new JDialogEstadisticaPaginaPorMinuto(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaPaginaPorMinuto.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemPaginasPorMinutoActionPerformed

    private void jItemLecturasPorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemLecturasPorPeriodoActionPerformed
        // TODO add your handling code here:

        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogEstadisticaLecturasPorPeriodo jDialogEstadisticaLecturasPorPeriodo = new JDialogEstadisticaLecturasPorPeriodo(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogEstadisticaLecturasPorPeriodo.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemLecturasPorPeriodoActionPerformed

    private void jItemResumenGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemResumenGeneralActionPerformed
        // TODO add your handling code here:
        if (cbPerfil.getSelectedItem() != null) {
            if (tbLibros.getRowCount() > 0 || tbLibrosTerminados.getRowCount() > 0) {
                JDialogResumenGeneral jDialogResumenGeneral = new JDialogResumenGeneral(this, rootPaneCheckingEnabled, perfilSeleccionado);
                jDialogResumenGeneral.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "El perfil seleccionado no tiene libros agregados..", "Advertencia", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un perfil.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jItemResumenGeneralActionPerformed

    private void jItemMenuEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemMenuEditarPerfilActionPerformed
        // TODO add your handling code here:

        JDialogEditarPerfil jDialogEditarPerfil = new JDialogEditarPerfil(this, rootPaneCheckingEnabled);
        jDialogEditarPerfil.setVisible(true);
    }//GEN-LAST:event_jItemMenuEditarPerfilActionPerformed

    private void cargarElementos() {

        cargarCbPerfil();
        cargarTablaLibrosPorLeer();
        cargarTablaLibrosTerminados();

        grillaLibrosEnLectura1.clear();

        libroLecturaSeleccionada = null;
//        perfilSeleccionado = null;
        libroLecturaTerminadasSeleccionada = null;
        libroEnEstadoLeyendoSeleccionada = null;

    }

    private void cargarCbPerfil() {

        List<Perfil> liPerfiles = perfilUtil.leerArchivo();

        DefaultComboBoxModel modelPerfiles = new DefaultComboBoxModel(liPerfiles.toArray());

        /*
         * Esto evita que el cbPerfil se quede seleccionado con el primer elemento 
         * cada vez que se selecciona otro o se actualiza(btn)
         */
        perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

        cbPerfil.setModel(modelPerfiles);

        cbPerfil.setSelectedItem(perfilSeleccionado);

    }

    private void cargarTablaLibrosPorLeer() {

        if (cbPerfil.getSelectedItem() != null) {

            perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

            List<Lectura> listaLibrosPorLeer = lecturaUtilImpl.getListadoLibrosPorLeerPorPerfil(perfilSeleccionado.getId());

            // System.out.println("ENTRO AL CARGAR  LIBROS POR LEER");
            //  System.out.println(perfilSeleccionado.getId());
            grillaLibrosPorLeer1.setLecturas(listaLibrosPorLeer);

        } else {
            System.out.println("Error al cargar la tabla libros, el combobox debe tener un elemento seleccionado.");
        }

    }

    private void cargarTablaLibrosTerminados() {

        if (cbPerfil.getSelectedItem() != null) {

            perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

            List<Lectura> listaLibrosPorLeer = lecturaUtilImpl.getListadoLibrosTerminadosPorPerfil(perfilSeleccionado.getId());

            // System.out.println("ENTRO AL CARGAR  LIBROS TERMINADOS");
            // System.out.println(perfilSeleccionado.getId());
            grillaLibrosTerminados1.setLecturas(listaLibrosPorLeer);

        } else {
            System.out.println("Error al cargar la tabla libros TERMINADOS, el combobox debe tener un elemento seleccionado.");
        }

    }

    private void cargarTablaLecturasDeLibrosTerminados() {

        if (cbPerfil.getSelectedItem() != null && libroLecturaTerminadasSeleccionada != null) {

            perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

            List<Lectura> listaLibrosEnLectura = lecturaUtilImpl.getListadoLibrosEnLecturaPorPerfilYLibro(perfilSeleccionado.getId(), libroLecturaTerminadasSeleccionada.getLibro());

            // System.out.println("ENTRO AL CARGAR   LECTURAS DE LIBROS TERMINANDOS");
            // System.out.println(perfilSeleccionado.getId());
            grillaLibrosEnLectura1.setLecturas(listaLibrosEnLectura);

        } else {
            System.out.println("Error al cargar la tabla libros EN LECTURA, el combobox debe tener un elemento seleccionado.");
        }
    }

    private void cargarTablaLibrosEnLectura() {

        if (cbPerfil.getSelectedItem() != null && libroLecturaSeleccionada != null) {

            perfilSeleccionado = (Perfil) cbPerfil.getSelectedItem();

            List<Lectura> listaLibrosEnLectura = lecturaUtilImpl.getListadoLibrosEnLecturaPorPerfilYLibro(perfilSeleccionado.getId(), libroLecturaSeleccionada.getLibro());

            //  System.out.println("ENTRO AL CARGAR  LIBROS EN LECTURA");
            //  System.out.println(perfilSeleccionado.getId());
            grillaLibrosEnLectura1.setLecturas(listaLibrosEnLectura);

        } else {
            System.out.println("Error al cargar la tabla libros EN LECTURA, el combobox debe tener un elemento seleccionado.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JfPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarLectura;
    private javax.swing.JButton btnEditarLectura;
    private javax.swing.JButton btnEditarLecturaLibroTerminado;
    private javax.swing.JButton btnEliminarLibroTerminado;
    private javax.swing.JComboBox<String> cbPerfil;
    private com.gustavo.guardarlibros.vista.grillas.GrillaLibrosEnLectura grillaLibrosEnLectura1;
    private com.gustavo.guardarlibros.vista.grillas.GrillaLibrosPorLeer grillaLibrosPorLeer1;
    private com.gustavo.guardarlibros.vista.grillas.GrillaLibrosTerminados grillaLibrosTerminados1;
    private javax.swing.JMenuItem jItemEstadisticaActividadDeLectura;
    private javax.swing.JMenuItem jItemEstadisticaEstadoDeMisLibros;
    private javax.swing.JMenuItem jItemEstadisticaLecturasPorAutor;
    private javax.swing.JMenuItem jItemEstadisticaProgresoPorLibro;
    private javax.swing.JMenuItem jItemLecturasPorPeriodo;
    private javax.swing.JMenuItem jItemMenuEditarLibro;
    private javax.swing.JMenuItem jItemMenuEditarPerfil;
    private javax.swing.JMenuItem jItemNuevoLibro;
    private javax.swing.JMenuItem jItemNuevoPerfil;
    private javax.swing.JMenuItem jItemPaginasPorMinuto;
    private javax.swing.JMenuItem jItemResumenGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBarra;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuEstadisticas;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JPanel jPaneLeerAEnLectura;
    private javax.swing.JPanel jPaneLibrosTerminados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelEnLectura;
    private javax.swing.JPanel jPanelEnLecturaATerminados;
    private javax.swing.JPanel jPanelInternoDeLeerAEnLectura;
    private javax.swing.JPanel jPanelLibrosPorLeer;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbLectura;
    private javax.swing.JTable tbLibros;
    private javax.swing.JTable tbLibrosTerminados;
    // End of variables declaration//GEN-END:variables
}
